export const PAGE = {
  headline1: "The Tech-First",
  headline2: "Landing Page",
  headlineItalic: "Design Agency",
  lead:
    "TechBinaries combines stunning UI/UX with premium landing page development services to build fast, high-converting digital experiences that turn your traffic into revenue.",
};

export const HERO_PHONE_COUNTRY_CODES = [
  "+92", "+1", "+44", "+971", "+91", "+61", "+49", "+966", "+65", "+86",
];

export const GROWTH = {
  kicker: "Why performance pages",
  title: "Features Built for",
  titleLine2: "",
  titleAccent: "Maximum ROI",
  lead:
    "Our high-converting landing page design elements combine to optimize your traffic and maximize revenue.",
  pillars: [
    {
      n: "01",
      k: "Visual & Engaging Page Design",
      v: "High-impact visuals",
      d: "We blend high-impact imagery and engaging short videos to tell your brand story faster, boosting user engagement and landing page conversions.",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&q=80&auto=format&fit=crop",
      imageAlt: "Visual landing page design with high-impact imagery and engaging media",
    },
    {
      n: "02",
      k: "Conversion-Focused Design",
      v: "Clear CTAs & copy",
      d: "We craft compelling headlines, clear subheadlines, and prominent calls-to-action that seamlessly guide your visitors toward a single, high-value conversion goal.",
      image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1400&q=80&auto=format&fit=crop",
      imageAlt: "Conversion-focused landing page layout with headlines and calls-to-action",
    },
    {
      n: "03",
      k: "Lead Capture Page Design",
      v: "Optimized lead forms",
      d: "Our strategically structured, high-converting lead generation landing page design features optimized input fields and forms designed to capture emails, registrations, or qualified project inquiries.",
      image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1400&q=80&auto=format&fit=crop",
      imageAlt: "Lead capture landing page with optimized registration and inquiry forms",
    },
    {
      n: "04",
      k: "Social Proof Integration",
      v: "Trust & credibility",
      d: "We strategically embed client testimonials, industry trust badges, and partner logos to build immediate credibility and maximize your page's conversion rates.",
      image: "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=1400&q=80&auto=format&fit=crop",
      imageAlt: "Landing page social proof with client testimonials and trust badges",
    },
  ],
};

export const COST = {
  image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1400&q=80&auto=format&fit=crop",
  imageAlt: "Marketing team reviewing underperforming campaign landing pages",
  kicker: "Where campaigns fail",
  title: 'Why "Cheap" Landing Pages',
  titleAccent: "Fail?",
  lead:
    "Many companies treat landing page design as an afterthought, using rigid templates or low-cost agencies.",
  failures: [
    {
      stat: "400%",
      label: "Conversion gap",
      d: "The massive conversion rate increase engineered UI/UX layouts achieve over standard, unoptimized pages.",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=900&q=80&auto=format&fit=crop",
      imageAlt: "Conversion rate analytics comparing optimized and unoptimized landing page layouts",
      theme: "perf",
    },
    {
      stat: "30%",
      label: "Abandonment rate",
      d: "The immediate visitor abandonment rate if your landing page takes longer than six seconds to load.",
      image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&q=80&auto=format&fit=crop",
      imageAlt: "Landing page load performance metrics and visitor bounce analytics",
      theme: "arch",
    },
    {
      stat: "34%",
      label: "Sales opportunity",
      d: "Drop in average conversion potential when dropping or neglecting strategically placed client trust signals.",
      image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=900&q=80&auto=format&fit=crop",
      imageAlt: "Client trust signals and social proof elements on a high-converting landing page",
      theme: "obs",
    },
    {
      stat: "266%",
      label: "Lead drop",
      d: "Lead growth generated by using a single, dedicated call-to-action instead of multiple competing navigation links.",
      image: "https://images.unsplash.com/photo-1574887427561-d3d5d58c9273?w=900&q=80&auto=format&fit=crop",
      imageAlt: "Single call-to-action landing page design focused on lead generation",
      theme: "a11y",
    },
  ],
  close:
    "But skimping on intentional UI/UX layout and optimized performance doesn't save money; it directly subsidizes your competitors and burns your ad budget.",
};

export const PROCESS = [
  {
    num: "01",
    title: "Strategic Discovery",
    d: "Provide your campaign objectives, audience demographics, unique value proposition, and key performance metrics. We align these with your brand guidelines to map out an engineering plan tailored specifically for your target market.",
    meta: "",
  },
  {
    num: "02",
    title: "Architecture & Wireframing",
    d: "We conduct deep competitor analysis and user behavioral research to inform our layout choices. From there, we build comprehensive structural wireframes that explicitly map out content hierarchy, visual flow, and friction-free user journeys.",
    meta: "",
  },
  {
    num: "03",
    title: "High-Fidelity UI/UX Design",
    d: "We craft custom, modern, creative landing page design interfaces utilizing psychological color theory, clean layouts, and intuitive interface design. Every element is strategically positioned to capture user attention and reduce cognitive load.",
    meta: "",
  },
  {
    num: "04",
    title: "High-Performance Engineering",
    d: "We, as a landing page development agency, translate the approved visuals into clean, production-grade code. We prioritize fast-loading landing pages, flawless cross-browser compatibility, and pixel-perfect responsiveness across all devices.",
    meta: "",
  },
  {
    num: "05",
    title: "Rigorous QA & Optimization",
    d: "Before the deployment phase, we execute comprehensive SEO landing page design testing. We audit form integrations, tracking scripts, mobile responsive breakpoints, and speed optimizations to guarantee an absolute zero-error launch.",
    meta: "",
  },
  {
    num: "06",
    title: "Deployment & Analytics Monitoring",
    d: "Post-launch, we actively track user behaviors, bounce rates, and total conversions. You receive comprehensive, data-backed performance reports along with clear optimization insights to continually scale your conversions.",
    meta: "",
  },
];

export const STACK = [
  { group: "Frontend", items: [{ name: "Next.js", v: "15.x", role: "Page framework" }, { name: "React", v: "19", role: "Interactive UI" }, { name: "TypeScript", v: "5.x", role: "Reliability" }, { name: "Tailwind", v: "4.x", role: "Design implementation" }]},
  { group: "Backend", items: [{ name: "Node.js", v: "22 LTS", role: "Campaign APIs" }, { name: "Edge Functions", v: "Latest", role: "Low-latency logic" }, { name: "GraphQL", v: "Latest", role: "Content delivery" }, { name: "Python", v: "3.12", role: "Attribution analysis" }]},
  { group: "Data", items: [{ name: "GA4", v: "Latest", role: "Event analytics" }, { name: "PostHog", v: "Latest", role: "Funnel insights" }, { name: "BigQuery", v: "Latest", role: "Attribution modeling" }, { name: "S3", v: "-", role: "Asset delivery" }]},
  { group: "Infra", items: [{ name: "Vercel", v: "Latest", role: "Global edge hosting" }, { name: "Cloudflare", v: "Latest", role: "Caching + DNS" }, { name: "Docker", v: "-", role: "Build portability" }, { name: "Terraform", v: "1.x", role: "IaC" }]},
];

export const FAQS = [
  {
    q: "What dictates the baseline landing page design cost?",
    a: "There is no single flat fee because every business brings unique criteria. The final investment depends entirely on your project's scope, custom visual assets, layout complexity, and the integration of systems. To get an accurate custom quote aligned with your exact goals, reach out to contact our team.",
  },
  {
    q: "How do you determine your landing page design price?",
    a: "Our packaging is never rigid because we don't use generic, cookie-cutter templates. Pricing depends on multiple dynamic factors, including advanced feature integrations, responsive breakpoints, and custom copywriting. Contact our team to receive a tailored, transparent estimate built for your technical requirements.",
  },
  {
    q: "What design framework creates a truly high-converting landing page design?",
    a: "It requires balancing a fast code stack, an intentional above-the-fold value proposition, single-goal user paths, and strategic social proof for a high-converting landing page design. Removing distracting secondary links ensures your visitors stay focused exclusively on your primary conversion goal.",
  },
  {
    q: "How do you approach B2B landing page design differently from B2C layouts?",
    a: "Business-to-business layouts prioritize friction-free lead qualification and deep professional credibility. We minimize cognitive load while integrating deep educational depth, corporate trust signals, and structured form captures to successfully turn business traffic into verified sales pipeline inquiries.",
  },
  {
    q: "What elements are mandatory in a real estate landing page design?",
    a: "High-performance property and community layouts must prioritize immersive, fast-loading visual imagery, hyper-clear unit layout options, interactive asset maps, and highly accessible scheduling fields. This clear structure makes it easy for premium buyers to book direct construction site visits or request pricing documentation effortlessly.",
  },
  {
    q: "Why does a PPC landing page design require a specialized layout structure?",
    a: "Paid campaigns demand tight message match consistency between your active advertisement and your page's H1 headline. In our PPC landing page design, by eliminating distracting global navigation menus and streamlining your form fields, we drastically reduce immediate bounce rates and preserve your ad spend budget.",
  },
  {
    q: "What is the fastest strategy to improve landing page conversion rate metrics?",
    a: "With our conversion rate optimization landing page services, we start by resolving technical speed bottlenecks, shaving down loading times by optimizing code and compressing assets. Follow up by stripping away non-essential input fields from your capture forms, deploying high-impact video elements, and executing precise visual A/B tests to optimize your revenue potential.",
  },
  {
    q: "How does a strategic Google Ads landing page design lower your cost-per-click?",
    a: "Google rewards highly relevant pages with a strong Quality Score, directly lowering your acquisition costs. We align your primary headline perfectly with your active ad copy, eliminate distracting site navigation, and optimize mobile performance to ensure you convert maximum traffic while preserving your ad spend budget.",
  },
];

export const CTA = {
  headline: "Stop Bleeding",
  headlineItalic: "Ad Spend.",
  lead:
    "Optimize your marketing funnel with premium code and data-driven custom landing page design built to maximize your ROI.",
  primaryCta: { label: "Book a discovery call", href: "/contact" },
  email: "hello@techbinaries.com",
  rows: [
    { k: "Response", v: "Within 24h" },
    { k: "Launch window", v: "2-4 weeks" },
    { k: "Primary focus", v: "CRO + speed" },
    { k: "Engagement", v: "Fixed or T&M" },
  ],
};
